### ISSUE TITLE
obtainAuthHeaders failing because the issuer has no registration endpoint.

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/solid-nextcloud#54]
```sh
root@5d67c38c9e1f:/app# ./node_modules/.bin/jest test/surface/fetch-pod-root.test.ts 
(node:48) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  test/surface/fetch-pod-root.test.ts
  ● Alice's storage root › is an ldp BasicContainer

    Dynamic Registration could not be completed because the issuer has no registration endpoint.

      at ClientRegistrar.performDynamicRegistration (node_modules/solid-auth-fetcher/src/login/oidc/ClientRegistrar.ts:56:13)
      at ClientRegistrar.getClient (node_modules/solid-auth-fetcher/src/login/oidc/ClientRegistrar.ts:86:25)
      at OidcLoginHandler.handle (node_modules/solid-auth-fetcher/src/login/oidc/OidcLoginHandler.ts:86:42)
      at Object.getAuthFetcher (node_modules/solid-auth-fetcher/src/obtainAuthHeaders.ts:39:19)
```

**Comment by michielbdejong** [comment]
```
root@5d67c38c9e1f:/app# curl -ki https://server/.well-known/openid-configuration
HTTP/1.1 404 Not Found
```

Maybe related to https://github.com/pdsinterop/solid-nextcloud/issues/46
